PILOT-1292 Use init container for running migrations
PilotDataPlatform/metadata pull request #33
Opened 2022-07-12 15:26 UTC by erikdvlp

## Summary

- Change Docker files to run Alembic migrations in their own container / build stage.
- Move local default Postgres credentials from `docker-compose.yaml` to `config.py`.

## JIRA Issues

https://indocconsortium.atlassian.net/browse/PILOT-1292

## Type of Change

- [x] Refactor or reformatting

## Testing

Are there any new or updated tests to validate the changes?

- [ ] Yes
- [x] No

## Test Directions

- Run the service locally and ensure that migrations run.
- Compare to the [project service](https://github.com/PilotDataPlatform/project) for consistency of approach.

2022-07-18 14:56 UTC, vmoshynskyi requested changes
Please check my comments.

2022-07-18 14:56 UTC, vmoshynskyi commented on docker-compose.yaml
> +      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI:-postgresql://postgres:postgres@metadata_db_1:5432/metadata}
As I understand it won't work in most cases with `metadata_db_1`:
```suggestion
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI:-postgresql://postgres:postgres@db:5432/metadata}
```

2022-07-18 14:56 UTC, vmoshynskyi commented on Dockerfile
> -CMD ["./uvicorn_starter.sh"]
What output docker image we will use? And what entrypoint it will have if we don't use `uvicorn_starter.sh` anymore?

2022-07-18 16:25 UTC, erikdvlp commented on .github/workflows/test_docker_compose.yml
> +          docker network create pilot-network
Removed.

2022-07-18 16:25 UTC, erikdvlp commented on docker-compose.yaml
> +      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI:-postgresql://postgres:postgres@metadata_db_1:5432/metadata}
I modified Alembic's config to not use an environment variable for its database connection.

2022-07-18 16:26 UTC, erikdvlp commented on Dockerfile
> -CMD ["./uvicorn_starter.sh"]
I updated the Docker files to use `metadata-image` with an entrypoint.

2022-07-18 20:30 UTC, erikdvlp commented on .github/workflows/test_docker_compose.yml
> +          docker exec metadata_web_1 poetry run pytest --verbose -c tests/pytest.ini
This whole thing should be reworked, but in a separate task.

2022-07-19 17:05 UTC, vmoshynskyi requested changes
Everything is good. A couple of final edits.

2022-07-19 17:05 UTC, vmoshynskyi commented on Jenkinsfile
> +            sh 'docker rmi $imagename:project-$commit'
Also here:
```suggestion
            sh 'docker rmi $imagename:alembic-$commit-CAC'
            sh 'docker rmi $imagename:metadata-$commit-CAC'
```

2022-07-19 18:58 UTC, erikdvlp commented on Jenkinsfile
> +                customImage = docker.build('$imagename:alembic-$commit', '--target alembic-image .')
You're right, thanks for catching these.

2022-07-20 17:39 UTC, merged