PILOT-1525: Add custom metadata kafka producer for item CRUD activities
PilotDataPlatform/metadata pull request #46
Opened 2022-08-26 15:51 UTC by afmam

## Summary

- Created custom metadata kafka producer to replace kafka-connector that is initiated at startup. This producer will send messages for each metadata item action (CRUD) to a respective topic.
- Implemented an avro schema for message serialization/validation before sending.

## JIRA Issues

https://indocconsortium.atlassian.net/browse/PILOT-1525

## Type of Change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
## Testing

Are there any new or updated tests to validate the changes?

- [X] Yes
- [ ] No

## Test Directions

1. Spin up a consumer that subscribes to the same topic that the producer sends the messages to.
2. Execute metadata item CRUD action (e.g., `POST /v1/item`)
3. After message is consumed by the consumer deserialize the message and validate with the same avro schema used by the producer as such below:
```
from fastavro import schemaless_reader, validate
from fastavro import schema
import io
imported_schema = schema.load_schema('metadata.items.avsc')
message_reader = io.BytesIO(msg.value)
message_decoded = schemaless_reader(message_reader, imported_schema)
# prevent writers schema changes to be promotable to readers schema
is_valid = validate(message_decoded, imported_schema, raise_errors=False) # should return True
```

2022-08-30 14:09 UTC, erikdvlp requested changes
Can you run the pre-commit please?

2022-09-07 14:35 UTC, afmam commented on docker-compose.yaml
> +      - zookeeper
Updated docker compose with this. It'll help immensely with development

2022-09-07 14:35 UTC, afmam commented
> Can you run the pre-commit please?

Ran pre-commit

2022-09-07 14:41 UTC, erikdvlp approved these changes

2022-09-13 16:19 UTC, merged