PILOT-1769 Configure logger levels
PilotDataPlatform/metadata pull request #64
Opened 2022-10-04 19:46 UTC by erikdvlp

## Summary

- Update common package to `0.1.0`.
- Add variables to the app config to control logger levels.
- Set all logger levels to 30 (warning) except for the error handler at 40 (error).

## JIRA Issues

https://indocconsortium.atlassian.net/browse/PILOT-1769

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

## Testing

Are there any new or updated tests to validate the changes?

- [x] No

## Test Directions

N/A

2022-10-04 19:54 UTC, erikdvlp commented
@hugoantunes Please also let me know if the health check logging spam is fixed either by this or [your previous work](https://indocconsortium.atlassian.net/browse/PILOT-1753) or not as I think they are related.

2022-10-05 09:02 UTC, hugoantunes commented on app/config.py
> +    LOG_LEVEL_STDERR = 40
can we change to more understandable values?
https://docs.python.org/3/library/logging.html#logging-levels

2022-10-05 09:55 UTC, hugoantunes requested changes

2022-10-05 09:55 UTC, hugoantunes commented on app/config.py
> +    LOG_LEVEL_STDERR = 40
Can you change it to more understandable values? 
https://docs.python.org/3/library/logging.html#logging-levels

2022-10-05 09:55 UTC, hugoantunes commented
@erikdvlp the other PR fixed the logging spam.

2022-10-05 09:56 UTC, hugoantunes commented
> @hugoantunes Please also let me know if the health check logging spam is fixed either by this or [your previous work](https://indocconsortium.atlassian.net/browse/PILOT-1753) or not as I think they are related.


@erikdvlp the other PR fixed the logging spam.

2022-10-05 12:42 UTC, erikdvlp commented on app/config.py
> +    LOG_LEVEL_STDERR = 40
Done.

2022-10-05 12:43 UTC, hugoantunes approved these changes

2022-10-05 12:55 UTC, merged